// Design-sync entry: everything the design agent can import from window.AlfaUI.
// Panel (shadcn/ui, Tailwind) + sitio público (Catálogo Alfa, alfa.css).
export * from '@/components/ui/alert';
export * from '@/components/ui/avatar';
export * from '@/components/ui/badge';
export * from '@/components/ui/breadcrumb';
export * from '@/components/ui/button';
export * from '@/components/ui/card';
export * from '@/components/ui/checkbox';
export * from '@/components/ui/collapsible';
export * from '@/components/ui/dialog';
export * from '@/components/ui/dropdown-menu';
export * from '@/components/ui/empty';
export * from '@/components/ui/icon';
export * from '@/components/ui/input';
export * from '@/components/ui/label';
export * from '@/components/ui/navigation-menu';
export * from '@/components/ui/pagination';
export * from '@/components/ui/placeholder-pattern';
export * from '@/components/ui/select';
export * from '@/components/ui/separator';
export * from '@/components/ui/sheet';
export * from '@/components/ui/sidebar';
export * from '@/components/ui/skeleton';
export * from '@/components/ui/sonner';
export * from '@/components/ui/spinner';
export * from '@/components/ui/switch';
export * from '@/components/ui/table';
export * from '@/components/ui/textarea';
export * from '@/components/ui/toggle-group';
export * from '@/components/ui/toggle';
export * from '@/components/ui/tooltip';
export * from '@/components/alfa/brand';
export * from '@/components/alfa/photo';
export * from '@/components/alfa/vehicle-card';
export * from '@/components/alfa/producto-card';
export * from '@/components/alfa/producto-catalogo';
export * from '@/components/alfa/galeria';
export * from '@/components/alfa/entregas';
export * from '@/components/alfa/site-header';
export * from '@/components/alfa/site-footer';
export * from '@/components/alfa/boton-whatsapp';
export { default as BotonWhatsapp } from '@/components/alfa/boton-whatsapp';
export { cn } from '@/lib/utils';
export { toast } from 'sonner';
